--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with parking;

package body PolyORB_HI_Generated.Subprograms is

  procedure parking_enter_analyze_spg
   renames parking.enter;

  procedure parking_leave_analyze_spg
   renames parking.leave;

  procedure parking_counter_spg
   renames parking.counter;

end PolyORB_HI_Generated.Subprograms;
