--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Types is

  type License_Plate is
   new Standard.Integer;

  --  license_plate'Object_Size ~= 32 bits

  License_Plate_Default_Value : constant License_Plate :=
   0;

  type Car_Counter is
   new Standard.Integer;

  --  car_counter'Object_Size ~= 32 bits

  Car_Counter_Default_Value : constant Car_Counter :=
   0;

end PolyORB_HI_Generated.Types;
