--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Subprograms is

  procedure parking_enter_analyze_spg;

  procedure parking_leave_analyze_spg;

  procedure parking_counter_spg;

end PolyORB_HI_Generated.Subprograms;
